# generated by datamodel-codegen:
#   filename:  https://gauravkhurana.com/practise-api/openapi.yaml
#   timestamp: 2026-04-27T06:10:48+00:00

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field


class Money(BaseModel):
    value: float | None = Field(None, examples=[599.0])
    currency: str | None = Field("INR", examples=["INR"])


class Address(BaseModel):
    line1: str | None = Field(None, examples=["123 Main Street"])
    line2: str | None = None
    city: str | None = Field(None, examples=["Mumbai"])
    state: str | None = Field(None, examples=["Maharashtra"])
    postal_code: str | None = Field(None, alias="postalCode", examples=["400001"])
    country: str | None = Field("IN", examples=["IN"])


class Pagination(BaseModel):
    page: int | None = Field(None, examples=[1])
    limit: int | None = Field(None, examples=[10])
    total: int | None = Field(None, examples=[100])
    total_pages: int | None = Field(None, alias="totalPages", examples=[10])
    has_next: bool | None = Field(None, alias="hasNext", examples=[True])
    has_prev: bool | None = Field(None, alias="hasPrev", examples=[False])


class ResponseMeta(BaseModel):
    request_id: UUID | None = Field(None, alias="requestId")
    timestamp: AwareDatetime | None = None
    version: str | None = Field(None, examples=["v1"])
    pagination: Pagination | None = None


class Detail(BaseModel):
    field: str | None = None
    code: str | None = None
    message: str | None = None


class Error(BaseModel):
    code: str | None = Field(None, examples=["NOT_FOUND"])
    message: str | None = Field(None, examples=["Resource not found"])
    trace_id: str | None = Field(None, alias="traceId")
    timestamp: AwareDatetime | None = None
    details: list[Detail] | None = None


class ErrorResponse(BaseModel):
    success: bool | None = Field(None, examples=[False])
    error: Error | None = None


class Data(BaseModel):
    deleted: bool | None = Field(None, examples=[True])
    id: str | None = None


class DeleteResponse(BaseModel):
    success: bool | None = Field(None, examples=[True])
    data: Data | None = None


class Status(StrEnum):
    healthy = "healthy"
    unhealthy = "unhealthy"


class Data1(BaseModel):
    status: Status | None = None
    service: str | None = None
    version: str | None = None
    timestamp: AwareDatetime | None = None


class HealthResponse(BaseModel):
    success: bool | None = None
    data: Data1 | None = None


class Data2(BaseModel):
    status: str | None = None
    database: str | None = None
    biller_count: int | None = Field(None, alias="billerCount")


class DbHealthResponse(BaseModel):
    success: bool | None = None
    data: Data2 | None = None


class TokenResponse(BaseModel):
    access_token: str | None = None
    token_type: str | None = Field(None, examples=["Bearer"])
    expires_in: int | None = Field(None, examples=[3600])
    refresh_token: str | None = None
    scope: str | None = None


class User(BaseModel):
    id: str | None = None
    email: str | None = None
    name: str | None = None
    scopes: list[str] | None = None


class AuthMethod(StrEnum):
    api_key = "api_key"
    bearer = "bearer"
    basic = "basic"
    oauth2 = "oauth2"


class Data3(BaseModel):
    user: User | None = None
    auth_method: AuthMethod | None = Field(None, alias="authMethod")


class AuthMeResponse(BaseModel):
    success: bool | None = None
    data: Data3 | None = None


class BillerCategory(StrEnum):
    telecom = "telecom"
    electricity = "electricity"
    water = "water"
    gas = "gas"
    broadband = "broadband"
    dth = "dth"
    insurance = "insurance"
    credit_card = "credit_card"
    loan = "loan"
    municipal_tax = "municipal_tax"


class BillStatus(StrEnum):
    pending = "pending"
    paid = "paid"
    overdue = "overdue"
    partially_paid = "partially_paid"
    cancelled = "cancelled"


class PaymentStatus(StrEnum):
    initiated = "initiated"
    processing = "processing"
    completed = "completed"
    failed = "failed"
    cancelled = "cancelled"
    refunded = "refunded"


class PaymentMethodType(StrEnum):
    upi = "upi"
    credit_card = "credit_card"
    debit_card = "debit_card"
    net_banking = "net_banking"
    wallet = "wallet"


class KycStatus(StrEnum):
    pending = "pending"
    verified = "verified"
    rejected = "rejected"


class Biller(BaseModel):
    id: str | None = Field(None, examples=["biller-airtel-postpaid"])
    name: str | None = Field(None, examples=["airtel"])
    display_name: str | None = Field(None, alias="displayName", examples=["Airtel Postpaid"])
    category: BillerCategory | None = None
    logo_url: AnyUrl | None = Field(None, alias="logoUrl")
    description: str | None = None
    supported_payment_modes: list[PaymentMethodType] | None = Field(
        None, alias="supportedPaymentModes"
    )
    fetch_bill_supported: bool | None = Field(None, alias="fetchBillSupported")
    partial_payment_allowed: bool | None = Field(None, alias="partialPaymentAllowed")
    min_amount: float | None = Field(None, alias="minAmount", ge=0.0)
    max_amount: float | None = Field(None, alias="maxAmount")
    customer_id_label: str | None = Field(None, alias="customerIdLabel", examples=["Mobile Number"])
    customer_id_pattern: str | None = Field(
        None,
        alias="customerIdPattern",
        description="Regex pattern for validation",
        examples=["^[6-9][0-9]{9}$"],
    )
    is_active: bool | None = Field(None, alias="isActive")
    created_at: AwareDatetime | None = Field(None, alias="createdAt")
    updated_at: AwareDatetime | None = Field(None, alias="updatedAt")


class BillerInput(BaseModel):
    name: str = Field(..., max_length=50, min_length=2)
    display_name: str = Field(..., alias="displayName", max_length=100, min_length=2)
    category: BillerCategory
    logo_url: AnyUrl | None = Field(None, alias="logoUrl")
    description: str | None = Field(None, max_length=500)
    supported_payment_modes: list[PaymentMethodType] | None = Field(
        None, alias="supportedPaymentModes"
    )
    fetch_bill_supported: bool | None = Field(True, alias="fetchBillSupported")
    partial_payment_allowed: bool | None = Field(False, alias="partialPaymentAllowed")
    min_amount: float | None = Field(1, alias="minAmount", ge=0.0)
    max_amount: float | None = Field(100000, alias="maxAmount")
    customer_id_label: str | None = Field("Customer ID", alias="customerIdLabel")
    customer_id_pattern: str | None = Field(None, alias="customerIdPattern")
    is_active: bool | None = Field(True, alias="isActive")


class BillerPatch(BaseModel):
    display_name: str | None = Field(None, alias="displayName")
    description: str | None = None
    min_amount: float | None = Field(None, alias="minAmount")
    max_amount: float | None = Field(None, alias="maxAmount")
    is_active: bool | None = Field(None, alias="isActive")


class BillerResponse(BaseModel):
    success: bool | None = None
    data: Biller | None = None
    meta: ResponseMeta | None = None


class BillersListResponse(BaseModel):
    success: bool | None = None
    data: list[Biller] | None = None
    meta: ResponseMeta | None = None


class Datum(BaseModel):
    category: BillerCategory | None = None
    count: int | None = None
    display_name: str | None = Field(None, alias="displayName")


class CategoriesResponse(BaseModel):
    success: bool | None = None
    data: list[Datum] | None = None


class AutoPay(BaseModel):
    enabled: bool | None = None
    payment_method_id: str | None = Field(None, alias="paymentMethodId")
    max_amount: float | None = Field(None, alias="maxAmount")
    days_before: int | None = Field(None, alias="daysBefore")


class Bill(BaseModel):
    id: str | None = None
    user_id: str | None = Field(None, alias="userId")
    biller_id: str | None = Field(None, alias="billerId")
    biller_name: str | None = Field(None, alias="billerName")
    customer_identifier: str | None = Field(None, alias="customerIdentifier")
    customer_name: str | None = Field(None, alias="customerName")
    nickname: str | None = None
    amount: Money | None = None
    due_date: date | None = Field(None, alias="dueDate")
    bill_date: date | None = Field(None, alias="billDate")
    bill_period: str | None = Field(None, alias="billPeriod")
    status: BillStatus | None = None
    auto_pay: AutoPay | None = Field(None, alias="autoPay")
    created_at: AwareDatetime | None = Field(None, alias="createdAt")
    updated_at: AwareDatetime | None = Field(None, alias="updatedAt")


class BillInput(BaseModel):
    user_id: str = Field(..., alias="userId")
    biller_id: str = Field(..., alias="billerId")
    customer_identifier: str = Field(..., alias="customerIdentifier", max_length=20, min_length=4)
    customer_name: str | None = Field(None, alias="customerName")
    nickname: str | None = Field(None, max_length=50)
    amount: float = Field(..., ge=1.0)
    currency: str | None = "INR"
    due_date: date | None = Field(None, alias="dueDate")
    bill_date: date | None = Field(None, alias="billDate")
    bill_period: str | None = Field(None, alias="billPeriod")
    status: BillStatus | None = None


class BillPatch(BaseModel):
    nickname: str | None = None
    amount: float | None = None
    due_date: date | None = Field(None, alias="dueDate")
    status: BillStatus | None = None


class BillResponse(BaseModel):
    success: bool | None = None
    data: Bill | None = None
    meta: ResponseMeta | None = None


class BillsListResponse(BaseModel):
    success: bool | None = None
    data: list[Bill] | None = None
    meta: ResponseMeta | None = None


class ByStatus(BaseModel):
    count: int | None = None
    total_amount: float | None = Field(None, alias="totalAmount")


class Total(BaseModel):
    count: int | None = None
    total_amount: float | None = Field(None, alias="totalAmount")


class Data4(BaseModel):
    by_status: dict[str, ByStatus] | None = Field(None, alias="byStatus")
    total: Total | None = None


class BillsSummaryResponse(BaseModel):
    success: bool | None = None
    data: Data4 | None = None


class Data5(Bill):
    fetched_at: AwareDatetime | None = Field(None, alias="fetchedAt")
    message: str | None = None


class BillFetchResponse(BaseModel):
    success: bool | None = None
    data: Data5 | None = None


class PaymentMethod(BaseModel):
    id: str | None = None
    type: PaymentMethodType | None = None


class Failure(BaseModel):
    code: str | None = None
    reason: str | None = None


class Payment(BaseModel):
    id: str | None = None
    bill_id: str | None = Field(None, alias="billId")
    user_id: str | None = Field(None, alias="userId")
    biller_name: str | None = Field(None, alias="billerName")
    amount: Money | None = None
    convenience_fee: float | None = Field(None, alias="convenienceFee")
    total_amount: Money | None = Field(None, alias="totalAmount")
    payment_method: PaymentMethod | None = Field(None, alias="paymentMethod")
    status: PaymentStatus | None = None
    transaction_id: str | None = Field(None, alias="transactionId")
    reference_number: str | None = Field(None, alias="referenceNumber")
    failure: Failure | None = None
    processed_at: AwareDatetime | None = Field(None, alias="processedAt")
    created_at: AwareDatetime | None = Field(None, alias="createdAt")


class PaymentInput(BaseModel):
    bill_id: str = Field(..., alias="billId")
    amount: float = Field(..., ge=1.0)
    currency: str | None = "INR"
    payment_method_id: str | None = Field(None, alias="paymentMethodId")
    payment_method_type: PaymentMethodType | None = Field(None, alias="paymentMethodType")


class PaymentResponse(BaseModel):
    success: bool | None = None
    data: Payment | None = None
    meta: ResponseMeta | None = None


class PaymentsListResponse(BaseModel):
    success: bool | None = None
    data: list[Payment] | None = None
    meta: ResponseMeta | None = None


class Completed(BaseModel):
    count: int | None = None
    total_amount: float | None = Field(None, alias="totalAmount")


class Data6(BaseModel):
    by_status: dict[str, Any] | None = Field(None, alias="byStatus")
    completed: Completed | None = None


class PaymentStatsResponse(BaseModel):
    success: bool | None = None
    data: Data6 | None = None


class Refund(BaseModel):
    amount: float | None = None
    reason: str | None = None
    processed_at: AwareDatetime | None = Field(None, alias="processedAt")


class Data7(Payment):
    refund: Refund | None = None


class RefundResponse(BaseModel):
    success: bool | None = None
    data: Data7 | None = None


class Card(BaseModel):
    last_four: str | None = Field(None, alias="lastFour")
    network: str | None = None
    expiry_month: int | None = Field(None, alias="expiryMonth")
    expiry_year: int | None = Field(None, alias="expiryYear")
    holder_name: str | None = Field(None, alias="holderName")


class Bank(BaseModel):
    name: str | None = None
    account_last_four: str | None = Field(None, alias="accountLastFour")


class Wallet(BaseModel):
    provider: str | None = None
    wallet_id: str | None = Field(None, alias="walletId")


class PaymentMethod1(BaseModel):
    id: str | None = None
    user_id: str | None = Field(None, alias="userId")
    type: PaymentMethodType | None = None
    display_name: str | None = Field(None, alias="displayName")
    is_default: bool | None = Field(None, alias="isDefault")
    is_active: bool | None = Field(None, alias="isActive")
    upi_id: str | None = Field(None, alias="upiId")
    card: Card | None = None
    bank: Bank | None = None
    wallet: Wallet | None = None
    created_at: AwareDatetime | None = Field(None, alias="createdAt")
    updated_at: AwareDatetime | None = Field(None, alias="updatedAt")


class CardNetwork(StrEnum):
    visa = "visa"
    mastercard = "mastercard"
    amex = "amex"
    rupay = "rupay"
    discover = "discover"


class PaymentMethodInput(BaseModel):
    user_id: str = Field(..., alias="userId")
    type: PaymentMethodType
    display_name: str = Field(..., alias="displayName", max_length=50, min_length=2)
    is_default: bool | None = Field(False, alias="isDefault")
    upi_id: str | None = Field(None, alias="upiId", description="Required for type=upi")
    card_last_four: str | None = Field(
        None, alias="cardLastFour", description="Required for card types", pattern="^[0-9]{4}$"
    )
    card_network: CardNetwork | None = Field(None, alias="cardNetwork")
    card_expiry_month: int | None = Field(None, alias="cardExpiryMonth", ge=1, le=12)
    card_expiry_year: int | None = Field(None, alias="cardExpiryYear", ge=2024)
    card_holder_name: str | None = Field(None, alias="cardHolderName")
    bank_name: str | None = Field(None, alias="bankName")
    bank_account_last_four: str | None = Field(None, alias="bankAccountLastFour")
    wallet_provider: str | None = Field(None, alias="walletProvider")
    wallet_id: str | None = Field(None, alias="walletId")


class PaymentMethodResponse(BaseModel):
    success: bool | None = None
    data: PaymentMethod1 | None = None
    meta: ResponseMeta | None = None


class PaymentMethodsListResponse(BaseModel):
    success: bool | None = None
    data: list[PaymentMethod1] | None = None
    meta: ResponseMeta | None = None


class Datum1(BaseModel):
    type: PaymentMethodType | None = None
    display_name: str | None = Field(None, alias="displayName")
    description: str | None = None
    convenience_fee: float | None = Field(None, alias="convenienceFee")


class PaymentTypesResponse(BaseModel):
    success: bool | None = None
    data: list[Datum1] | None = None


class User1(BaseModel):
    id: str | None = None
    email: EmailStr | None = None
    phone: str | None = None
    first_name: str | None = Field(None, alias="firstName")
    last_name: str | None = Field(None, alias="lastName")
    kyc_status: KycStatus | None = Field(None, alias="kycStatus")
    address: Address | None = None
    created_at: AwareDatetime | None = Field(None, alias="createdAt")
    updated_at: AwareDatetime | None = Field(None, alias="updatedAt")


class UserInput(BaseModel):
    email: EmailStr
    phone: str | None = Field(None, pattern="^\\+?[0-9]{10,15}$")
    first_name: str = Field(..., alias="firstName", max_length=50, min_length=1)
    last_name: str | None = Field(None, alias="lastName", max_length=50)
    kyc_status: KycStatus | None = Field(None, alias="kycStatus")
    address: Address | None = None


class UserPatch(BaseModel):
    email: EmailStr | None = None
    phone: str | None = None
    first_name: str | None = Field(None, alias="firstName")
    last_name: str | None = Field(None, alias="lastName")
    kyc_status: KycStatus | None = Field(None, alias="kycStatus")
    address: Address | None = None


class UserResponse(BaseModel):
    success: bool | None = None
    data: User1 | None = None
    meta: ResponseMeta | None = None


class UsersListResponse(BaseModel):
    success: bool | None = None
    data: list[User1] | None = None
    meta: ResponseMeta | None = None


class Type(StrEnum):
    payment = "payment"
    refund = "refund"
    reversal = "reversal"
    cashback = "cashback"
    fee = "fee"


class Datum2(BaseModel):
    id: str | None = None
    payment_id: str | None = Field(None, alias="paymentId")
    type: Type | None = None
    amount: Money | None = None
    status: str | None = None
    description: str | None = None
    created_at: AwareDatetime | None = Field(None, alias="createdAt")


class TransactionsListResponse(BaseModel):
    success: bool | None = None
    data: list[Datum2] | None = None
    meta: ResponseMeta | None = None


class KycVerification(BaseModel):
    previous_status: KycStatus | None = Field(None, alias="previousStatus")
    new_status: KycStatus | None = Field(None, alias="newStatus")
    verified_at: AwareDatetime | None = Field(None, alias="verifiedAt")


class Data8(User1):
    kyc_verification: KycVerification | None = Field(None, alias="kycVerification")


class KycVerificationResponse(BaseModel):
    success: bool | None = None
    data: Data8 | None = None


class UploadedFile(BaseModel):
    id: str | None = Field(None, examples=["file-abc123"])
    filename: str | None = Field(
        None, description="Generated filename", examples=["file-abc123-document.pdf"]
    )
    original_name: str | None = Field(
        None,
        alias="originalName",
        description="Original uploaded filename",
        examples=["document.pdf"],
    )
    mime_type: str | None = Field(None, alias="mimeType", examples=["application/pdf"])
    size: int | None = Field(None, description="File size in bytes", examples=[102400])
    uploaded_at: AwareDatetime | None = Field(None, alias="uploadedAt")
    user_id: str | None = Field(
        None, alias="userId", description="ID of user who uploaded the file"
    )
    metadata: dict[str, str] | None = Field(
        None, description="Optional metadata (description, category, etc.)"
    )


class Checksum(BaseModel):
    algorithm: str | None = Field(None, examples=["SHA-256"])
    value: str | None = Field(None, description="Hex-encoded hash of file content")


class Data9(BaseModel):
    file: UploadedFile | None = None
    url: str | None = Field(
        None, description="URL to access the file", examples=["/v1/files/file-abc123"]
    )
    checksum: Checksum | None = None


class FileUploadResponse(BaseModel):
    success: bool | None = None
    data: Data9 | None = None
    meta: ResponseMeta | None = None


class UploadedItem(BaseModel):
    file: UploadedFile | None = None
    url: str | None = None


class FailedItem(BaseModel):
    filename: str | None = None
    error: str | None = None


class Summary(BaseModel):
    total: int | None = None
    successful: int | None = None
    failed: int | None = None


class Data10(BaseModel):
    uploaded: list[UploadedItem] | None = None
    failed: list[FailedItem] | None = None
    summary: Summary | None = None


class MultiFileUploadResponse(BaseModel):
    success: bool | None = None
    data: Data10 | None = None
    meta: ResponseMeta | None = None


class FileResponse(BaseModel):
    success: bool | None = None
    data: UploadedFile | None = None
    meta: ResponseMeta | None = None


class FilesListResponse(BaseModel):
    success: bool | None = None
    data: list[UploadedFile] | None = None
    meta: ResponseMeta | None = None
